version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "3001:8000"
    volumes:
      - ./backend/app:/code/app
      - ./backend/engines:/code/engines
      - ./backend/data:/code/data
      - ./backend/services:/code/services
    environment:
      - GEMINI_API_KEY=AIzaSyD_udmO5Y10dgHtnoRLC4jomQJYxs4xtXY
    command: python real_data_server.py
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_BACKEND_URL=http://localhost:3001
    command: npm start
    depends_on:
      - backend